import { Test, TestingModule } from '@nestjs/testing';
import { getLoggerToken } from 'nestjs-pino';
import { AiService } from './ai.service';
import { AI_CLIENT } from './ai-client.interface';
import AIClientException from 'src/exception/AIClientException';

describe('AiService', () => {
  let service: AiService;
  let aiClient: { generateReply: jest.Mock };
  let logger: {
    info: jest.Mock;
    error: jest.Mock;
    debug: jest.Mock;
    warn: jest.Mock;
  };

  beforeEach(async () => {
    aiClient = { generateReply: jest.fn() };
    logger = {
      info: jest.fn(),
      error: jest.fn(),
      debug: jest.fn(),
      warn: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AiService,
        { provide: AI_CLIENT, useValue: aiClient },
        { provide: getLoggerToken(AiService.name), useValue: logger },
      ],
    }).compile();

    service = module.get<AiService>(AiService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  it('returns the reply generated by the underlying AI client', async () => {
    aiClient.generateReply.mockResolvedValue('Hello, how can I help?');

    const result = await service.generateReply('Danilo', 'Hi there');

    expect(aiClient.generateReply).toHaveBeenCalledWith('Hi there');
    expect(result).toBe('Hello, how can I help?');
  });

  it('logs and throws an AIClientException when the underlying AI client fails', async () => {
    aiClient.generateReply.mockRejectedValue(new Error('upstream unavailable'));

    await expect(service.generateReply('Danilo', 'Hi there')).rejects.toThrow(
      AIClientException,
    );

    expect(logger.error).toHaveBeenCalledWith(
      expect.stringContaining('AI service unavailable for Danilo'),
    );
  });
});
